import type { Answer, GraphNode } from "./types";

const GATES = [
  "w2",
  "se",
  "payapps",
  "rental",
  "interest",
  "capgain",
  "crypto",
  "retirement",
  "hsa",
  "education",
  "estimates",
  "dependents",
  "personal_mortgage",
  "age_blind",
  "claimed_dependent",
  "deduction_choice",
  "jurisdiction",
];

function unk(next: string[], label = "I don't know"): Answer {
  return { id: "unknown", label, edge: "Unknown", next };
}

function choice(
  id: string,
  label: string,
  next: string[],
  edge?: string,
): Answer {
  return { id, label, edge: edge ?? label, next };
}

const FLOW = ["form_1040"];

export const nodes: GraphNode[] = [
  {
    id: "year",
    section: "start",
    kind: "question",
    title: "Tax year",
    chart: "Tax year being final-checked",
    prompt: "Which tax year is on the return you are final-checking?",
    help: "In early October 2026, a 2025 return can still be in the extension window (file-by date with an extension is October 15, 2026). 2026 figures are included only where a published source was found. This is the year on the return, not a suggestion to file a new one.",
    answers: [
      choice("y2024", "2024", ["filing_status"], "2024"),
      choice("y2025", "2025", ["filing_status"], "2025"),
      choice("y2026", "2026", ["filing_status"], "2026"),
      unk(["filing_status"]),
    ],
  },
  {
    id: "filing_status",
    section: "start",
    kind: "question",
    title: "Filing status",
    chart: "Filing status on the return",
    prompt: "What filing status is on the prepared return?",
    help: "The status changes the standard deduction. Each income topic opens only if you say it applies. Unknown does not pick a status for you.",
    answers: [
      choice("single", "Single", GATES, "Single"),
      choice("mfj", "Married filing jointly", GATES, "MFJ"),
      choice("mfs", "Married filing separately", [...GATES, "mfs_spouse"], "MFS"),
      choice("hoh", "Head of household", GATES, "Head of household"),
      choice("qss", "Qualifying surviving spouse", GATES, "Surviving spouse"),
      unk(GATES),
    ],
  },
  {
    id: "w2",
    section: "income",
    kind: "question",
    title: "W-2 wages",
    chart: "W-2 wages?",
    prompt: "Does the prepared return include W-2 wages?",
    help: "A yes answer opens Form 1040 line 1a for verification. It does not tell you to add a W-2.",
    answers: [
      choice("yes", "Yes", ["check_w2", ...FLOW], "Yes"),
      choice("no", "No", ["note_w2_no"], "No"),
      unk(["flag_w2"]),
    ],
  },
  {
    id: "check_w2",
    section: "income",
    kind: "check",
    title: "Form 1040 wages",
    chart: "Form 1040 line 1a — W-2 box 1 wages. Verify the prepared return. Not an instruction to start a form.",
    help: "2025 Form 1040 line 1a is the total from Forms W-2, box 1. For any other year, confirm the line on that year's form.",
    flowsTo: FLOW,
  },
  {
    id: "note_w2_no",
    section: "income",
    kind: "check",
    title: "No W-2 on this path",
    chart: "No W-2 wages on this path",
    help: "Nothing is added to the wage checklist from this answer.",
  },
  {
    id: "flag_w2",
    section: "income",
    kind: "check",
    title: "W-2 unknown",
    chart: "W-2 wages unknown — verify whether line 1a was considered",
    help: "The wage line stays flagged. No wage amount is assumed.",
  },
  {
    id: "se",
    section: "se",
    kind: "question",
    title: "Self-employment",
    chart: "Self-employment or 1099-NEC income?",
    prompt: "Does the prepared return include self-employment or Form 1099-NEC income?",
    answers: [
      choice("yes", "Yes", ["se_entity"], "Yes"),
      choice("no", "No", ["note_se_no"], "No"),
      unk(["flag_se"]),
    ],
  },
  {
    id: "note_se_no",
    section: "se",
    kind: "check",
    title: "No Schedule C on this path",
    chart: "No self-employment branch on this path",
    help: "Schedule C and Schedule SE stay closed.",
  },
  {
    id: "flag_se",
    section: "se",
    kind: "check",
    title: "Self-employment unknown",
    chart: "Self-employment unknown — verify whether Schedule C was considered",
    help: "Do not open Schedule C as if the answer were yes.",
  },
  {
    id: "se_entity",
    section: "se",
    kind: "question",
    title: "Entity",
    chart: "Is the work a sole proprietorship or an entity?",
    prompt: "How is the work owned on the prepared return?",
    help: "A disregarded sole proprietorship is still checked on Schedule C. A partnership or S corporation is a K-1, not a new Schedule C started from this chart.",
    answers: [
      choice("sole", "Sole proprietor — no LLC and no corporation", ["se_count"], "Sole prop"),
      choice("llc_disregarded", "Single-member LLC taxed as a sole proprietorship", ["se_count"], "Disregarded LLC"),
      choice("partnership", "Partnership or multi-member LLC", ["check_entity_k1"], "Partnership"),
      choice("scorp", "S corporation", ["check_entity_k1"], "S corp"),
      unk(["flag_se", "se_count"]),
    ],
  },
  {
    id: "se_count",
    section: "se",
    kind: "question",
    title: "How many activities",
    chart: "How many sole-proprietor activities?",
    prompt: "How many separate activities have 1099-NEC or similar income?",
    help: "The 2025 Schedule C instructions say to use a separate Schedule C for each business. Naming them only tells the checklist what to look for.",
    answers: [
      choice("one", "One activity", ["se_names"], "One"),
      choice("two", "Two or more", ["se_names"], "Two or more"),
      unk(["schedule_c", "schedule_se", "flag_se", ...FLOW]),
    ],
  },
  {
    id: "se_names",
    section: "se",
    kind: "question",
    title: "Activity names",
    chart: "Name the sole-proprietor activities",
    prompt: "What are the activities? For two 1099-NEC jobs, name both.",
    help: "Leave this blank only by choosing unknown. The chart will not invent job names.",
    textInput: {
      placeholder: "Example shape: nursing and coding",
      answerId: "named",
      next: ["schedule_c", "schedule_se", "check_no_entity", ...FLOW],
      edge: "Named",
    },
    answers: [unk(["schedule_c", "schedule_se", "flag_se", ...FLOW])],
  },
  {
    id: "schedule_c",
    section: "flow",
    kind: "check",
    title: "Schedule C",
    chart:
      "Schedule C is for self-employment income and expenses, including 1099-NEC freelance jobs. Verify it on the prepared return. Not an instruction to start a form.",
    help: "2025 Schedule C line 1 includes Forms 1099-NEC. Line 31 goes to Schedule 1 line 3 and to Schedule SE line 2. One Schedule C per business.",
    tipId: "schedule_c",
    flowsTo: FLOW,
  },
  {
    id: "schedule_se",
    section: "se",
    kind: "check",
    title: "Schedule SE",
    chart:
      "Schedule SE — self-employment tax on sole-proprietor net profit. Verify it. The i button outlines the calculation. Not a tax computation.",
    help: "Publication 334 (2025) says Schedule SE is filed when net earnings are $400 or more. Net earnings were not entered here, so that threshold is not applied as a conclusion.",
    tipId: "se_tax",
    flowsTo: FLOW,
  },
  {
    id: "check_no_entity",
    section: "se",
    kind: "check",
    title: "No entity return",
    chart: "Verify the work is not reported on Form 1065 or Form 1120-S",
    help: "Use this only as a cross-check of the prepared return when the path says there is no partnership and no S corporation.",
  },
  {
    id: "check_entity_k1",
    section: "se",
    kind: "check",
    title: "K-1 instead of Schedule C",
    chart: "Entity path — verify Schedule E Part II or the K-1. Do not treat Schedule C as the entity return.",
    help: "A partnership or S corporation return is not prepared here. Confirm the K-1 the software already imported.",
    flowsTo: FLOW,
  },
  {
    id: "payapps",
    section: "payments",
    kind: "question",
    title: "Payment apps",
    chart: "Venmo, PayPal, or similar payment apps?",
    prompt: "Is there Venmo, PayPal, or similar payment-app activity to cross-check?",
    help: "Goods-and-services or other commercial payments are still filed even when Venmo, PayPal, or a similar app does not issue Form 1099-K. Being under the form threshold is not a reason to leave them off.",
    answers: [
      choice("yes", "Yes", ["pay_class"], "Yes"),
      choice("no", "No", ["note_pay_no"], "No"),
      unk(["flag_pay"]),
    ],
  },
  {
    id: "note_pay_no",
    section: "payments",
    kind: "check",
    title: "No payment-app activity",
    chart: "No payment-app branch",
    help: "Form 1099-K is not added from this answer.",
  },
  {
    id: "flag_pay",
    section: "payments",
    kind: "check",
    title: "Payment apps unknown",
    chart: "Payment-app activity unknown — no 1099-K rule applied",
    help: "The threshold is not applied, and no amount is invented.",
  },
  {
    id: "pay_class",
    section: "payments",
    kind: "question",
    title: "What the payments were",
    chart: "Personal transfers or goods and services?",
    prompt: "What were the payment-app receipts?",
    help: "Friends-and-family transfers are not goods-and-services payments. Goods-and-services payments can be reportable even when the app does not issue Form 1099-K.",
    answers: [
      choice("personal", "Personal / friends and family", ["check_personal"], "Personal"),
      choice("goods", "Goods and services (transactional)", ["pay_1099k"], "Goods and services"),
      choice("both", "Both", ["check_personal", "pay_1099k"], "Both"),
      unk(["flag_pay"]),
    ],
  },
  {
    id: "check_personal",
    section: "payments",
    kind: "check",
    title: "Personal transfers",
    chart: "Personal transfers — verify they were not reported as business income",
    help: "No 1099-K filing threshold is applied to friends-and-family transfers.",
  },
  {
    id: "pay_1099k",
    section: "payments",
    kind: "question",
    title: "Was a 1099-K issued?",
    chart: "Did a platform issue Form 1099-K?",
    prompt: "Was Form 1099-K issued for the goods-and-services payments?",
    tipId: "ten99k",
    answers: [
      choice("issued", "Yes, a 1099-K was issued", ["check_1099k_form", ...FLOW], "Form issued"),
      choice("no_form", "No form was generated", ["pay_amount"], "No form"),
      unk(["pay_amount"]),
    ],
  },
  {
    id: "check_1099k_form",
    section: "payments",
    kind: "check",
    title: "Verify Form 1099-K",
    chart: "Form 1099-K was issued — verify that form on the prepared return",
    help: "Match the form to the income lines already on the prepared return. Receiving the form is not an instruction to start a new schedule.",
    tipId: "ten99k",
    flowsTo: FLOW,
  },
  {
    id: "pay_amount",
    section: "payments",
    kind: "question",
    title: "Payment-app amount",
    chart: "Amount and transaction count",
    prompt:
      "If you know them, enter the goods-and-services total and the number of transactions. Unknown leaves the threshold unapplied.",
    help: "Do not guess. A blank unknown path still says goods-and-services income is reportable when no form was generated.",
    textInput: {
      placeholder: "Amount and count, only if you know them",
      answerId: "entered",
      next: ["check_manual", ...FLOW],
      edge: "Amount entered",
    },
    answers: [unk(["check_manual", ...FLOW], "Amount unknown")],
    tipId: "ten99k",
  },
  {
    id: "check_manual",
    section: "payments",
    kind: "check",
    title: "Report without a 1099-K",
    chart:
      "Goods-and-services income is still reportable when the platform does not issue Form 1099-K. Verify the manual entry. Not an instruction to start a form.",
    help: "The 2025 federal threshold is applied only when both an amount and a transaction count were entered.",
    tipId: "ten99k",
    flowsTo: FLOW,
  },
  {
    id: "rental",
    section: "rental",
    kind: "question",
    title: "Rental real estate",
    chart: "Rental real estate on the return?",
    prompt: "Does the prepared return include rental real estate?",
    answers: [
      choice("yes", "Yes", ["rental_count"], "Yes"),
      choice("no", "No", ["note_rental_no"], "No"),
      unk(["flag_rental"]),
    ],
  },
  {
    id: "note_rental_no",
    section: "rental",
    kind: "check",
    title: "No rental branch",
    chart: "No Schedule E rental branch",
    help: "Schedule E Part I stays closed.",
  },
  {
    id: "flag_rental",
    section: "rental",
    kind: "check",
    title: "Rental unknown",
    chart: "Rental activity unknown — verify whether Schedule E Part I was considered",
    help: "Detail questions stay closed until you know the return has a rental.",
  },
  {
    id: "rental_count",
    section: "rental",
    kind: "question",
    title: "How many properties",
    chart: "How many rental properties?",
    prompt: "How many rental properties are on the return?",
    answers: [
      choice("one", "Exactly one", ["check_one_property", "rental_own"], "One"),
      choice("two_three", "Two or three", ["rental_own"], "2 or 3"),
      choice("more", "More than three", ["rental_own"], "More than 3"),
      unk(["flag_rental", "rental_own"]),
    ],
  },
  {
    id: "check_one_property",
    section: "rental",
    kind: "check",
    title: "One Schedule E column",
    chart: "One property — verify a single Schedule E column",
    help: "2025 Schedule E Part I has columns A, B, and C. One property should not fill a second column.",
  },
  {
    id: "rental_own",
    section: "rental",
    kind: "question",
    title: "Ownership",
    chart: "Who owns the rental?",
    prompt: "How is the rental owned?",
    answers: [
      choice("whole", "Wholly owned", ["check_whole", "rental_debt"], "Wholly owned"),
      choice("partial", "Partial ownership (not through an entity)", ["rental_debt"], "Partial"),
      choice("entity", "Owned through a partnership or S corporation", ["check_entity_k1"], "Entity"),
      unk(["flag_rental", "rental_debt"]),
    ],
  },
  {
    id: "check_whole",
    section: "rental",
    kind: "check",
    title: "Wholly owned",
    chart: "Wholly owned — verify it is not a Form 1065 rental",
    help: "The 2025 Schedule E property section asks about ownership. The exact percentage line is flagged because it was not separately confirmed beyond the property information block.",
  },
  {
    id: "rental_debt",
    section: "rental",
    kind: "question",
    title: "Rental mortgage",
    chart: "Is the rental mortgaged?",
    prompt: "Is there a mortgage on the rental property?",
    answers: [
      choice("paid_off", "Paid off — no mortgage", ["check_paid_off", "rental_history"], "Paid off"),
      choice("mortgage", "There is a mortgage", ["rental_history"], "Mortgage"),
      unk(["rental_history"]),
    ],
  },
  {
    id: "check_paid_off",
    section: "rental",
    kind: "check",
    title: "No rental mortgage interest",
    chart: "Paid-off rental — verify Schedule E line 12 mortgage interest",
    help: "2025 Schedule E line 12 is mortgage interest paid to banks. Verify it is not claiming interest for a property the path describes as paid off.",
  },
  {
    id: "rental_history",
    section: "rental",
    kind: "question",
    title: "Rental history",
    chart: "When did the rental start, and was it on an earlier return?",
    prompt: "What is the rental history on the prepared return and the prior returns?",
    help: "A start year does not by itself say the depreciation schedule started that year.",
    answers: [
      choice(
        "prior_2019",
        "Began in 2019, same tenants, and it was on earlier returns",
        ["check_history", "schedule_e", "rental_tenant", "rental_alloc", "rental_depr", "rental_records", ...FLOW],
        "Since 2019",
      ),
      choice(
        "prior_other",
        "Began in a prior year and was on an earlier return",
        ["check_history", "schedule_e", "rental_tenant", "rental_alloc", "rental_depr", "rental_records", ...FLOW],
        "Prior year",
      ),
      choice(
        "first_year",
        "First year of the rental",
        ["schedule_e", "rental_tenant", "rental_alloc", "rental_depr", "rental_records", ...FLOW],
        "First year",
      ),
      unk(["flag_rental", "schedule_e", "rental_records", ...FLOW]),
    ],
  },
  {
    id: "check_history",
    section: "rental",
    kind: "check",
    title: "Prior-year rental",
    chart: "Rental was on earlier returns — verify those returns agree. Do not set a depreciation start year from this alone.",
    help: "Same tenants since 2019 does not answer square footage, tenant-paid expenses, or whether the depreciation worksheet is clean.",
  },
  {
    id: "schedule_e",
    section: "flow",
    kind: "check",
    title: "Schedule E",
    chart:
      "Schedule E is where rental property income and expenses go: rent collected and things like repairs, insurance, and depreciation. Verify it on the prepared return. Not an instruction to start a form.",
    help: "2025 lines to verify: line 2 days, line 3 rents, line 12 mortgage interest, line 17 utilities, line 18 depreciation, line 26 total.",
    tipId: "schedule_e",
    flowsTo: FLOW,
  },
  {
    id: "rental_tenant",
    section: "rental",
    kind: "question",
    title: "Tenant-paid expenses",
    chart: "Did a tenant pay water or other expenses?",
    prompt: "Did a tenant pay water or any other property expense directly?",
    answers: [
      choice("yes", "Yes", ["tenant_how"], "Yes"),
      choice("no", "No", ["note_tenant_no"], "No"),
      unk(["flag_tenant"]),
    ],
  },
  {
    id: "note_tenant_no",
    section: "rental",
    kind: "check",
    title: "No tenant-paid expenses",
    chart: "No tenant-paid expenses on this path",
    help: "Nothing is added to rents or utilities from this answer.",
  },
  {
    id: "flag_tenant",
    section: "rental",
    kind: "check",
    title: "Tenant-paid expenses unknown",
    chart: "Tenant-paid water or other expenses unknown — verify line 3 and line 17",
    help: "Publication 527 is not applied as if the answer were yes.",
  },
  {
    id: "tenant_how",
    section: "rental",
    kind: "question",
    title: "How tenant-paid amounts were reported",
    chart: "How did the return treat tenant-paid expenses?",
    prompt: "On the prepared return, how were tenant-paid expenses treated?",
    help: "Pub. 527 (2025) says a tenant's payment of your expense is rental income, and the expense can be deducted if it is deductible. This question only asks what the return already did.",
    answers: [
      choice("both", "In income and in the matching expense", ["check_tenant"], "Both sides"),
      choice("income_only", "Income only", ["check_tenant"], "Income only"),
      choice("expense_only", "Expense only", ["check_tenant"], "Expense only"),
      choice("omitted", "Left off both", ["check_tenant"], "Omitted"),
      unk(["check_tenant"]),
    ],
  },
  {
    id: "check_tenant",
    section: "rental",
    kind: "check",
    title: "Tenant-paid expenses",
    chart: "Verify tenant-paid amounts against Schedule E line 3 and the expense lines",
    help: "Utilities are line 17 on the 2025 Schedule E. Other expenses may be line 19. This is a cross-check, not an instruction to add income.",
  },
  {
    id: "rental_alloc",
    section: "rental",
    kind: "question",
    title: "Owner use vs rental use",
    chart: "Any owner use, or square-footage split?",
    prompt: "How is the property split between tenants and the owner?",
    answers: [
      choice("all_rental", "Entire property rented, no owner use", ["check_alloc"], "All rented"),
      choice("sqft", "Part of the property is owner-occupied (square footage)", ["sqft_docs"], "Square footage"),
      choice("days", "Personal-use days", ["check_alloc"], "Personal days"),
      choice("both", "Both a space split and personal-use days", ["sqft_docs", "check_alloc"], "Both"),
      unk(["flag_alloc"]),
    ],
  },
  {
    id: "sqft_docs",
    section: "rental",
    kind: "question",
    title: "Square footage",
    chart: "Is the square-footage split documented?",
    prompt: "Is the rental portion measured by square footage you can point to?",
    answers: [
      choice("yes", "Yes, square footage is documented", ["check_sqft"], "Documented"),
      choice("no", "No square-footage record", ["check_sqft"], "Not documented"),
      unk(["check_sqft"]),
    ],
  },
  {
    id: "check_sqft",
    section: "rental",
    kind: "check",
    title: "Square footage",
    chart: "Verify the rental portion. Pub. 527 allows square footage as a method. No percentage is computed here.",
    help: "Do not invent a square-footage percentage.",
  },
  {
    id: "check_alloc",
    section: "rental",
    kind: "check",
    title: "Use allocation",
    chart: "Verify Schedule E line 2 fair-rental and personal-use days",
    help: "Personal-use days and a room rental are different splits. The chart does not calculate either one.",
  },
  {
    id: "flag_alloc",
    section: "rental",
    kind: "check",
    title: "Allocation unknown",
    chart: "Owner/tenant allocation unknown — verify line 2 and any square-footage worksheet",
    help: "No allocation percentage is assumed.",
  },
  {
    id: "rental_depr",
    section: "rental",
    kind: "question",
    title: "Depreciation claimed",
    chart: "Does this return claim depreciation?",
    prompt: "Does the prepared return claim depreciation for the rental?",
    answers: [
      choice("yes", "Yes", ["check_depr"], "Claimed"),
      choice("no", "No", ["check_depr"], "Not claimed"),
      unk(["flag_depr"]),
    ],
  },
  {
    id: "check_depr",
    section: "rental",
    kind: "check",
    title: "Depreciation",
    chart: "Verify Schedule E line 18 and whether Form 4562 is attached for a 2025 reason",
    help: "2025 Schedule E instructions: attach Form 4562 for property first placed in service in 2025, listed property, or section 179 / amortization that began in 2025. A continuing worksheet is still checked even when Form 4562 is not attached.",
  },
  {
    id: "flag_depr",
    section: "rental",
    kind: "check",
    title: "Depreciation unknown",
    chart: "Whether depreciation was claimed is unknown — verify line 18",
    help: "Pub. 527 says depreciation is how cost is recovered. That is not a finding that this return missed it.",
  },
  {
    id: "rental_records",
    section: "rental",
    kind: "question",
    title: "Depreciation records",
    chart: "Do prior returns show a clean carry-forward depreciation schedule?",
    prompt:
      "Do the prior returns show a carry-forward depreciation schedule, and does anything look missing or incorrect?",
    help: "The age of the schedule does not change a preparation fee. Clean records versus missing or incorrect records is the question. The start year is not assumed.",
    tipId: "depr_records",
    answers: [
      choice("clean", "Prior returns show it, and it looks consistent", ["check_records_clean"], "Clean"),
      choice("problems", "Missing, or something looks incorrect", ["check_records_problem"], "Problems"),
      choice("no_prior", "No prior-year schedule (first year)", ["check_records_clean"], "No prior schedule"),
      unk(["flag_records"]),
    ],
  },
  {
    id: "check_records_clean",
    section: "rental",
    kind: "check",
    title: "Records look consistent",
    chart: "Carry-forward looks consistent — verify the worksheet matches the prior year. Not a fee change.",
    help: "Pub. 527 (2025) says to continue the same depreciation method for property placed in service before 2025.",
  },
  {
    id: "check_records_problem",
    section: "rental",
    kind: "check",
    title: "Records need work",
    chart: "Carry-forward missing or inconsistent — verify the worksheet. Extra preparation work is possible. No dollar amount is added.",
    help: "This flag does not reprice a quote and does not tell you the depreciation start year.",
  },
  {
    id: "flag_records",
    section: "rental",
    kind: "check",
    title: "Depreciation records unknown",
    chart: "Carry-forward cleanliness is unknown. Do not assume the schedule started in 2019. No fee is changed.",
    help: "The unknown path keeps any preparation quote where it was. Nothing is added or subtracted.",
    tipId: "depr_records",
  },
  {
    id: "interest",
    section: "invest",
    kind: "question",
    title: "Interest and dividends",
    chart: "Interest or ordinary dividends?",
    prompt: "Does the return include taxable interest or ordinary dividends?",
    answers: [
      choice("yes", "Yes", ["interest_threshold"], "Yes"),
      choice("no", "No", ["note_interest_no"], "No"),
      unk(["flag_interest"]),
    ],
  },
  {
    id: "note_interest_no",
    section: "invest",
    kind: "check",
    title: "No interest or dividends",
    chart: "No interest or dividend branch",
    help: "Schedule B stays closed.",
  },
  {
    id: "interest_threshold",
    section: "invest",
    kind: "question",
    title: "Schedule B threshold",
    chart: "Over $1,500 of taxable interest or ordinary dividends?",
    prompt: "Is the taxable interest or ordinary dividends over $1,500?",
    help: "2025 Schedule B instructions use “over $1,500 of taxable interest or ordinary dividends.” Other Schedule B triggers exist even under that amount.",
    answers: [
      choice("over", "Yes, over $1,500", ["check_sch_b", ...FLOW], "Over $1,500"),
      choice("under", "No, not over $1,500", ["check_interest_small"], "Not over"),
      unk(["flag_interest", "check_sch_b"]),
    ],
  },
  {
    id: "check_sch_b",
    section: "invest",
    kind: "check",
    title: "Schedule B",
    chart: "Schedule B — verify interest and ordinary dividends. Flows to Form 1040.",
    help: "Also verify Form 1040 lines for taxable interest and ordinary dividends on the 2025 form (lines 2b and 3b). Confirm those line numbers if the year is not 2025.",
    flowsTo: FLOW,
  },
  {
    id: "check_interest_small",
    section: "invest",
    kind: "check",
    title: "Under the Schedule B dollar test",
    chart: "Not over $1,500 — Schedule B may still be required for another listed reason",
    help: "Seller-financed mortgage interest, foreign accounts, and the other 2025 Schedule B triggers are not ruled out by the dollar test.",
  },
  {
    id: "flag_interest",
    section: "invest",
    kind: "check",
    title: "Interest unknown",
    chart: "Interest or dividends unknown — Schedule B flagged, not assumed",
    help: "The $1,500 test is not applied to a guessed amount.",
  },
  {
    id: "capgain",
    section: "invest",
    kind: "question",
    title: "Capital gains",
    chart: "Sales of stocks, funds, or other capital assets?",
    prompt: "Does the return report sales of capital assets (Form 1099-B or similar)?",
    tipId: "capital_gain",
    answers: [
      choice("yes", "Yes", ["check_capgain", ...FLOW], "Yes"),
      choice("no", "No", ["note_capgain_no"], "No"),
      unk(["flag_capgain"]),
    ],
  },
  {
    id: "note_capgain_no",
    section: "invest",
    kind: "check",
    title: "No capital-gain sales",
    chart: "No Schedule D sales branch",
    help: "Crypto has its own question.",
  },
  {
    id: "check_capgain",
    section: "invest",
    kind: "check",
    title: "Schedule D and Form 8949",
    chart: "Verify Form 8949 and Schedule D. They flow to Form 1040. Line numbers for the 1040 total are flagged if you are not on the 2025 form you have open.",
    help: "This check does not tell you to start Form 8949. It asks you to verify the forms the prepared return already uses.",
    flowsTo: FLOW,
  },
  {
    id: "flag_capgain",
    section: "invest",
    kind: "check",
    title: "Capital gains unknown",
    chart: "Capital-asset sales unknown — verify whether Form 8949 was considered",
    help: "No sale is assumed.",
  },
  {
    id: "crypto",
    section: "invest",
    kind: "question",
    title: "Digital assets",
    chart: "Crypto or other digital assets?",
    prompt: "Does the return involve cryptocurrency or other digital assets?",
    answers: [
      choice("sold", "Yes — sold, exchanged, or received as payment", ["check_crypto", "check_capgain", ...FLOW], "Disposed"),
      choice("held", "Held only — no disposal this year", ["check_crypto_held"], "Held only"),
      choice("no", "No", ["note_crypto_no"], "No"),
      unk(["flag_crypto"]),
    ],
  },
  {
    id: "note_crypto_no",
    section: "invest",
    kind: "check",
    title: "No digital assets",
    chart: "No digital-asset branch",
    help: "The Form 1040 digital-asset question is still worth a glance if you are unsure.",
  },
  {
    id: "check_crypto",
    section: "invest",
    kind: "check",
    title: "Digital asset disposals",
    chart: "Verify the Form 1040 digital-asset question and the 8949 / Schedule D entries. Not an instruction to start those forms.",
    help: "The exact checkbox position on the 2025 Form 1040 should be read off the prepared return. It is flagged rather than given a guessed line.",
    flowsTo: FLOW,
  },
  {
    id: "check_crypto_held",
    section: "invest",
    kind: "check",
    title: "Digital assets held",
    chart: "Verify the digital-asset question was answered. Holding alone does not open Form 8949 from this path.",
    help: "If a disposal happened and was not selected, go back and change the answer.",
  },
  {
    id: "flag_crypto",
    section: "invest",
    kind: "check",
    title: "Digital assets unknown",
    chart: "Digital assets unknown — verify the Form 1040 question",
    help: "No crypto sale is assumed.",
  },
  {
    id: "retirement",
    section: "other",
    kind: "question",
    title: "Retirement distributions",
    chart: "IRA or pension distributions (Form 1099-R)?",
    prompt: "Does the return include a retirement distribution?",
    answers: [
      choice("yes", "Yes", ["check_retire", ...FLOW], "Yes"),
      choice("no", "No", ["note_retire_no"], "No"),
      unk(["flag_retire"]),
    ],
  },
  {
    id: "note_retire_no",
    section: "other",
    kind: "check",
    title: "No retirement distribution",
    chart: "No Form 1099-R branch",
    help: "Nothing is added.",
  },
  {
    id: "check_retire",
    section: "other",
    kind: "check",
    title: "Form 1099-R",
    chart: "Verify Form 1099-R against the IRA and pension lines. Those line numbers are flagged — read them on the form.",
    help: "The 2025 Form 1040 still has an IRA and pension section. This tool does not store a line number it did not read off the form image, so the line stays flagged.",
    flowsTo: FLOW,
  },
  {
    id: "flag_retire",
    section: "other",
    kind: "check",
    title: "Retirement unknown",
    chart: "Retirement distributions unknown — verify whether a 1099-R was considered",
    help: "No distribution is assumed.",
  },
  {
    id: "hsa",
    section: "other",
    kind: "question",
    title: "HSA",
    chart: "Health savings account (Form 8889)?",
    prompt: "Does the return include HSA contributions or distributions?",
    answers: [
      choice("yes", "Yes", ["check_hsa", ...FLOW], "Yes"),
      choice("no", "No", ["note_hsa_no"], "No"),
      unk(["flag_hsa"]),
    ],
  },
  {
    id: "note_hsa_no",
    section: "other",
    kind: "check",
    title: "No HSA",
    chart: "No Form 8889 branch",
    help: "Nothing is added.",
  },
  {
    id: "check_hsa",
    section: "other",
    kind: "check",
    title: "Form 8889",
    chart: "Verify Form 8889. Contribution limits are not stored here, so no cap is shown.",
    help: "The deduction flows through Schedule 1 onto Form 1040. The Schedule 1 line number is flagged unless you are reading the 2025 form.",
    flowsTo: FLOW,
  },
  {
    id: "flag_hsa",
    section: "other",
    kind: "check",
    title: "HSA unknown",
    chart: "HSA unknown — verify whether Form 8889 was considered",
    help: "No contribution is assumed.",
  },
  {
    id: "education",
    section: "other",
    kind: "question",
    title: "Education",
    chart: "Education credit or student loan interest?",
    prompt: "Does the return include an education credit or student loan interest?",
    answers: [
      choice("credit", "Education credit (Form 8863)", ["check_edu", ...FLOW], "Form 8863"),
      choice("loan", "Student loan interest", ["check_edu", ...FLOW], "Student loan"),
      choice("both", "Both", ["check_edu", ...FLOW], "Both"),
      choice("no", "No", ["note_edu_no"], "No"),
      unk(["flag_edu"]),
    ],
  },
  {
    id: "note_edu_no",
    section: "other",
    kind: "check",
    title: "No education items",
    chart: "No education branch",
    help: "Nothing is added.",
  },
  {
    id: "check_edu",
    section: "other",
    kind: "check",
    title: "Education",
    chart: "Verify Form 8863 and/or student loan interest on Schedule 1. Line numbers are flagged.",
    help: "TurboTax Free Edition's published scope mentions student loan interest. That is a software note, not a reason to start a form.",
    flowsTo: FLOW,
  },
  {
    id: "flag_edu",
    section: "other",
    kind: "check",
    title: "Education unknown",
    chart: "Education items unknown — verify Form 8863 and student loan interest",
    help: "Nothing is assumed.",
  },
  {
    id: "estimates",
    section: "other",
    kind: "question",
    title: "Estimated tax",
    chart: "Estimated tax payments?",
    prompt: "Does the return include estimated tax payments?",
    help: "Estimated tax payments are amounts already paid during the year, usually quarterly, when withholding did not cover the tax. On a prepared return they are a credit against the tax, not a new form to start. Yes means those payments are on the return and should be verified.",
    tipId: "estimates",
    answers: [
      choice("yes", "Yes", ["check_est", ...FLOW], "Yes"),
      choice("no", "No", ["note_est_no"], "No"),
      unk(["flag_est"]),
    ],
  },
  {
    id: "note_est_no",
    section: "other",
    kind: "check",
    title: "No estimated payments",
    chart: "No estimated-tax branch",
    help: "Nothing is added.",
  },
  {
    id: "check_est",
    section: "other",
    kind: "check",
    title: "Estimated tax payments",
    chart: "Verify estimated tax payments on Form 1040. The 2025 Schedule E instructions refer to line 26 for an estimated-tax credit.",
    help: "Read line 26 on the form in front of you. Quarterly vouchers are Form 1040-ES. This does not compute a penalty.",
    flowsTo: FLOW,
  },
  {
    id: "flag_est",
    section: "other",
    kind: "check",
    title: "Estimated tax unknown",
    chart: "Estimated payments unknown — verify the payments section",
    help: "No payment is assumed.",
  },
  {
    id: "dependents",
    section: "other",
    kind: "question",
    title: "Dependents",
    chart: "Dependents on the return?",
    prompt: "Does the prepared return claim any dependents?",
    help: "This is not the question of whether someone else can claim you. That question is in the deduction branch.",
    answers: [
      choice("yes", "Yes", ["check_dependents", ...FLOW], "Yes"),
      choice("no", "No", ["note_dep_no"], "No"),
      unk(["flag_dep"]),
    ],
  },
  {
    id: "note_dep_no",
    section: "other",
    kind: "check",
    title: "No dependents claimed",
    chart: "No dependent-credit branch",
    help: "Nothing is added.",
  },
  {
    id: "check_dependents",
    section: "other",
    kind: "check",
    title: "Dependents",
    chart: "Verify the dependents section and Schedule 8812 if a child tax credit is on the return. Line numbers are flagged.",
    help: "Do not add a dependent from this chart.",
    flowsTo: FLOW,
  },
  {
    id: "flag_dep",
    section: "other",
    kind: "check",
    title: "Dependents unknown",
    chart: "Dependents unknown — verify the dependents section",
    help: "No credit is assumed.",
  },
  {
    id: "personal_mortgage",
    section: "deductions",
    kind: "question",
    title: "Personal mortgage",
    chart: "Personal mortgage on a home you live in?",
    prompt: "Is there a mortgage on a home you live in (not the rental question)?",
    help: "No mortgage does not decide standard deduction versus itemizing.",
    answers: [
      choice("no", "No mortgage", ["check_no_mortgage"], "No mortgage"),
      choice("yes", "Yes", ["check_mortgage"], "Mortgage"),
      unk(["flag_deduction"]),
    ],
  },
  {
    id: "check_no_mortgage",
    section: "deductions",
    kind: "check",
    title: "No personal mortgage",
    chart: "No personal mortgage — verify Schedule A is not claiming home mortgage interest. This does not choose the standard deduction.",
    help: "The rental mortgage is a separate question.",
  },
  {
    id: "check_mortgage",
    section: "deductions",
    kind: "check",
    title: "Home mortgage interest",
    chart: "If the return itemizes, verify home mortgage interest on Schedule A. Not a reason to start Schedule A.",
    help: "The 2025 Schedule A line for home mortgage interest should be read on the form. It is flagged here rather than numbered from memory.",
  },
  {
    id: "age_blind",
    section: "deductions",
    kind: "question",
    title: "Age or blindness",
    chart: "Age 65 or older, or blind, at year end?",
    prompt: "Were you (and a spouse on a joint return, if any) 65 or older or blind at the end of the tax year?",
    answers: [
      choice("no", "No", ["deduction_result"], "No"),
      choice("age", "65 or older", ["deduction_result"], "65 or older"),
      choice("blind", "Blind", ["deduction_result"], "Blind"),
      choice("both", "Both 65 or older and blind", ["deduction_result"], "Both"),
      unk(["deduction_result"]),
    ],
  },
  {
    id: "claimed_dependent",
    section: "deductions",
    kind: "question",
    title: "Claimed as a dependent",
    chart: "Can someone else claim you?",
    prompt: "Can another taxpayer claim you as a dependent?",
    answers: [
      choice("no", "No", ["deduction_result"], "No"),
      choice("yes", "Yes", ["deduction_result"], "Yes"),
      unk(["deduction_result"]),
    ],
  },
  {
    id: "mfs_spouse",
    section: "deductions",
    kind: "question",
    title: "Spouse itemizes",
    chart: "Does the spouse itemize on a separate return?",
    prompt: "If you are married filing separately, does your spouse itemize?",
    help: "Topic 551: if your spouse itemizes on a separate return, you cannot take the standard deduction.",
    answers: [
      choice("yes", "Yes, my spouse itemizes", ["deduction_result"], "Spouse itemizes"),
      choice("no", "No", ["deduction_result"], "Spouse does not"),
      unk(["deduction_result"]),
    ],
  },
  {
    id: "deduction_choice",
    section: "deductions",
    kind: "question",
    title: "Standard or itemized",
    chart: "What the prepared return deducted",
    prompt: "On the prepared federal return, which deduction is on Form 1040 line 12e?",
    help: "Compare that choice with the sourced standard deduction after you pick a year, status, and jurisdiction. This is not a recommendation to switch.",
    tipId: "std_vs_item",
    answers: [
      choice("standard", "Standard deduction", ["deduction_result"], "Standard"),
      choice("itemized", "Itemized on Schedule A", ["itemized_amount"], "Itemized"),
      unk(["deduction_result"]),
    ],
  },
  {
    id: "itemized_amount",
    section: "deductions",
    kind: "question",
    title: "Schedule A total",
    chart: "Schedule A total already on the return",
    prompt: "Enter the itemized total already on the prepared Schedule A, or choose unknown.",
    help: "This is the number the software already computed. It is not a new itemized return.",
    textInput: {
      placeholder: "Schedule A total from the prepared return",
      answerId: "entered",
      next: ["deduction_result"],
      edge: "Amount from return",
    },
    answers: [unk(["deduction_result"])],
    tipId: "std_vs_item",
  },
  {
    id: "jurisdiction",
    section: "deductions",
    kind: "question",
    title: "Jurisdiction",
    chart: "Which state? Do not guess LA.",
    prompt:
      "Which jurisdiction should location-specific checks use? If notes say “LA,” choose Louisiana, Los Angeles / California, or unknown. Nothing is guessed.",
    help: "State standard deductions and state prices stay closed until this is answered.",
    answers: [
      choice("louisiana", "Louisiana (IT-540)", ["deduction_result"], "Louisiana"),
      choice("california", "Los Angeles / California (Form 540)", ["ca_itemized", "deduction_result"], "California"),
      choice("federal", "Federal return only", ["deduction_result"], "Federal only"),
      choice("other", "A different state", ["deduction_result"], "Other state"),
      unk(["deduction_result"], "Unknown — LA not resolved"),
    ],
  },
  {
    id: "ca_itemized",
    section: "deductions",
    kind: "question",
    title: "California itemized total",
    chart: "California itemized total on the prepared Form 540, if any",
    prompt:
      "If the California return itemizes, enter that California total (not the federal Schedule A total). Otherwise choose unknown.",
    textInput: {
      placeholder: "California itemized total from the prepared return",
      answerId: "entered",
      next: ["deduction_result"],
      edge: "CA total",
    },
    answers: [unk(["deduction_result"])],
  },
  {
    id: "deduction_result",
    section: "deductions",
    kind: "check",
    title: "Deduction comparison",
    chart:
      "Standard vs itemized — sourced amounts for the selected year, status, and jurisdiction. Verify Form 1040 line 12e. Not a recommendation to change the return.",
    help: "Numbers are filled from the threshold tables. Missing inputs stay flagged.",
    tipId: "std_vs_item",
    flowsTo: FLOW,
  },
  {
    id: "flag_deduction",
    section: "deductions",
    kind: "check",
    title: "Deduction facts unknown",
    chart: "A deduction fact is unknown — do not treat a comparison as finished",
    help: "Go back and answer the open deduction questions, or leave them unknown on purpose.",
  },
  {
    id: "form_1040",
    section: "flow",
    kind: "check",
    title: "Form 1040",
    chart:
      "Form 1040 — Schedule C, Schedule E, and any other schedules this path turns up flow onto the main Form 1040. Verify the prepared return. Not an instruction to start a form.",
    help: "Line 11b is adjusted gross income and line 12e is the deduction on the 2025 form. Other lines are cited only when a stored source names them.",
    tipId: "form_1040",
  },
];

const byId = new Map(nodes.map((node) => [node.id, node]));

export function getNode(id: string): GraphNode {
  const node = byId.get(id);
  if (!node) {
    throw new Error(`Unknown graph node: ${id}`);
  }
  return node;
}

export function listNodes(): GraphNode[] {
  return nodes;
}
